#!/bin/bash
echo '1' > /proc/sys/net/ipv4/ip_forward 
echo '1' > /proc/sys/net/ipv4/tcp_syncookies
iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X
iptables -Z
iptables -P INPUT DROP 
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT 
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1452 
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
AICMP="0 3 3/4 4 11 12 14 16 18"
for tyicmp in $AICMP
do
	iptables -A INPUT -i ppp0 -p icmp --icmp-type $tyicmp -j ACCEPT
done
iptables -A INPUT -p TCP -i wlan0 --dport 22 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p TCP -i wlan0 --dport 80 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p TCP -i ppp0 --dport 80 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p TCP -i ppp0 --dport 443 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p TCP -i ppp0 --dport 110 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p TCP -i ppp0 --dport 53 --sport 1024:65534 -j ACCEPT 
iptables -A INPUT -p UDP -i ppp0 --dport 53 --sport 1024:65534 -j ACCEPT 

iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -d 0/0 -o ppp0 -j MASQUERADE

